apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ai-assistant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ai-assistant
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ai-assistant
    spec:
      containers:
        - name: ai-assistant
          image: "{{ .Values.services.aiAssistant.image }}:{{ .Values.services.aiAssistant.tag }}"
          ports:
            - containerPort: 8080
